message(STATUS)
message(STATUS "--------- General configuration for ${PROJECT_NAME} ${PROJECT_VERSION}")
message(STATUS "------------------ CMake options:")
message(STATUS "CMAKE_SOURCE_DIR =            ${CMAKE_SOURCE_DIR}")
message(STATUS "CMAKE_BINARY_DIR =            ${CMAKE_BINARY_DIR}")

message(STATUS "------------------ Build system:")
message(STATUS "Generator =                   ${CMAKE_GENERATOR}")
message(STATUS "CMAKE_CXX_COMPILER_ID =       ${CMAKE_CXX_COMPILER_ID}")
message(STATUS "CMAKE_CXX_COMPILER =          ${CMAKE_CXX_COMPILER}")
message(STATUS "CMAKE_CXX_COMPILER_VERSION =  ${CMAKE_CXX_COMPILER_VERSION}")
message(STATUS "CMAKE_BUILD_TYPE =            ${CMAKE_BUILD_TYPE}")

message(STATUS "------------------ Compiler flags:")
message(STATUS "CMAKE_CXX_FLAGS =             ${CMAKE_CXX_FLAGS}")
message(STATUS "CMAKE_CXX_FLAGS_DEBUG =       ${CMAKE_CXX_FLAGS_DEBUG}")
message(STATUS "CMAKE_CXX_FLAGS_RELEASE =     ${CMAKE_CXX_FLAGS_RELEASE}")
message(STATUS "CMAKE_EXE_LINKER_FLAGS =      ${CMAKE_EXE_LINKER_FLAGS}")

message(STATUS "------------------ Options:")
message(STATUS "ENABLE_UNIT_TESTS =           ${ENABLE_UNIT_TESTS}")
message(STATUS "OPT_ASAN =                    ${OPT_ASAN}")
message(STATUS "WARNINGS_AS_ERRORS =          ${WARNINGS_AS_ERRORS}")

message(STATUS "------------------ Status messages:")
message(STATUS "CURRENT UPLOAD TOOL IS:       ${AVR_UPLOADTOOL}")
message(STATUS "CURRENT PROGRAMMER IS:        ${AVR_PROGRAMMER}")
message(STATUS "CURRENT UPLOAD PORT IS:       ${AVR_UPLOADTOOL_PORT}")
message(STATUS "CURRENT UPLOAD TOOL OPTIONS ARE: ${AVR_UPLOADTOOL_OPTIONS}")
message(STATUS "CURRENT MCU IS SET TO:        ${AVR_MCU}")
message(STATUS "CURRENT H_FUSE IS SET TO:     ${AVR_H_FUSE}")
message(STATUS "CURRENT L_FUSE IS SET TO:     ${AVR_L_FUSE}")
message(STATUS)
